## Dubbo 服务提供者配置
spring:
  extend:
    dubbo:
      application:
        name: provider
      registry:
        address: zookeeper://127.0.0.1:2181
      protocol:
        name: dubbo
        port: 20880
      scan: com.tutorial.dubbo